### PR TITLE
Implement protocol for tuples

### PR DESCRIPTION
**Pull request by eksperimental**

### CODE REVIEW

**Comment by eksperimental** [comment]
Not too sure if we should include it, for the reasons stated in the Tuple documentation,

> A tuple may contain elements of different types, which are stored contiguously in memory. Accessing any element takes constant time, but modifying a tuple, which produces a shallow copy, takes linear time. Tuples are good for reading data while lists are better for traversals.

**Comment by Qqwy** [comment]
>  but modifying a tuple, which produces a shallow copy, takes linear time. 

This is exactly why an implementation was not provided previously, and I do not think we should add one now. Tuples are almost surely the wrong abstraction if you want to extract single elements from a collection one by one over time.

**Comment by eksperimental** [comment]
> > but modifying a tuple, which produces a shallow copy, takes linear time.
> 
> This is exactly why an implementation was not provided previously, and I do not think we should add one now. Tuples are almost surely the wrong abstraction if you want to extract single elements from a collection one by one over time.

Agreed!

**Comment by eksperimental** [comment]
now checking the loogs I see this https://github.com/Qqwy/elixir-extractable/commit/7e53a4c4bf96b792ee1056080c11e65ae882a6f4#diff-2e226072c084ce39606f6326b51df0b62ac63f2352438662465af7b4388f6bd1R83

**Pull request closed without merging**
