### PR TITLE
Faster map extract benchmark

### PR DESCRIPTION
**Pull request by Qqwy**
Related to #13, this is a benchmark to check the performance of different implementations of `extract` for maps (which might also be applicable for MapSets).

Running this benchmark on my machine yields the following:

```
$ mix run benchmarks/map_extract.exs 
Operating System: Linux
CPU Information: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
Number of Available Cores: 8
Available memory: 7.61 GB
Elixir 1.11.2
Erlang 23.0

Benchmark suite executing with the following configuration:
warmup: 2 s
time: 1 s
memory time: 1 s
parallel: 1
inputs: 10, 100, empty
Estimated total run time: 48 s

Benchmarking MapIterator with input 10...
Benchmarking MapIterator with input 100...
Benchmarking MapIterator with input empty...
Benchmarking MapKeys with input 10...
Benchmarking MapKeys with input 100...
Benchmarking MapKeys with input empty...
Benchmarking MapKeysSize with input 10...
Benchmarking MapKeysSize with input 100...
Benchmarking MapKeysSize with input empty...
Benchmarking MapList with input 10...
Benchmarking MapList with input 100...
Benchmarking MapList with input empty...

##### With input 10 #####
Name                  ips        average  deviation         median         99th %
MapKeysSize       12.34 M       81.01 ns ±10835.42%           0 ns         296 ns
MapList           10.64 M       94.00 ns ±13658.06%           0 ns         368 ns
MapKeys           10.44 M       95.83 ns ±19165.13%           0 ns         268 ns
MapIterator        1.77 M      564.74 ns  ±2266.35%         471 ns        1001 ns

Comparison: 
MapKeysSize       12.34 M
MapList           10.64 M - 1.16x slower +12.99 ns
MapKeys           10.44 M - 1.18x slower +14.81 ns
MapIterator        1.77 M - 6.97x slower +483.72 ns

Memory usage statistics:

Name           Memory usage
MapKeysSize           464 B
MapList               680 B - 1.47x memory usage +216 B
MapKeys               464 B - 1.00x memory usage +0 B
MapIterator          1032 B - 2.22x memory usage +568 B

**All measurements for memory usage were the same**

##### With input 100 #####
Name                  ips        average  deviation         median         99th %
MapKeysSize      853.10 K        1.17 μs   ±484.54%        1.08 μs        2.68 μs
MapKeys          844.04 K        1.18 μs   ±518.66%        1.08 μs        2.84 μs
MapList          119.24 K        8.39 μs    ±39.82%        8.08 μs       12.94 μs
MapIterator       72.67 K       13.76 μs    ±22.55%       13.18 μs       19.22 μs

Comparison: 
MapKeysSize      853.10 K
MapKeys          844.04 K - 1.01x slower +0.0126 μs
MapList          119.24 K - 7.15x slower +7.21 μs
MapIterator       72.67 K - 11.74x slower +12.59 μs

Memory usage statistics:

Name           Memory usage
MapKeysSize         1.67 KB
MapKeys             1.67 KB - 1.00x memory usage +0 KB
MapList             4.13 KB - 2.47x memory usage +2.45 KB
MapIterator         7.85 KB - 4.70x memory usage +6.18 KB

**All measurements for memory usage were the same**

##### With input empty #####
Name                  ips        average  deviation         median         99th %
MapList            1.93 B        0.52 ns  ±6854.19%           0 ns           0 ns
MapKeysSize        1.01 B        0.99 ns ±29150.80%           0 ns           0 ns
MapKeys            0.40 B        2.50 ns ±51753.43%           0 ns           0 ns
MapIterator      0.0483 B       20.71 ns ±55288.94%           0 ns           0 ns

Comparison: 
MapList            1.93 B
MapKeysSize        1.01 B - 1.90x slower +0.47 ns
MapKeys            0.40 B - 4.81x slower +1.98 ns
MapIterator      0.0483 B - 39.94x slower +20.19 ns

Memory usage statistics:

Name           Memory usage
MapList                 0 B
MapKeysSize             0 B - 1.00x memory usage +0 B
MapKeys                 0 B - 1.00x memory usage +0 B
MapIterator            16 B - ∞ x memory usage +16 B

**All measurements for memory usage were the same**

```

This clearly seems to indicate that a `Map.keys` with extra `map_size` check is the preferred one based on time and memory efficiency.

### CODE REVIEW

**Comment by eksperimental** [comment]
I share with you the results for my tests with maps with 10, 100, 1_000, 10_000, and  1_000_000 elements.
The results vary a bit from yours but are consistent across different runs.

```
Benchmark suite executing with the following configuration:
warmup: 2 s
time: 3 s
memory time: 1 s
parallel: 1
inputs: empty, 10, 100, 1_000, 10_000, 1_000_000
Estimated total run time: 4.20 min

Benchmarking MapIterator with input empty...
Benchmarking MapIterator with input 10...
Benchmarking MapIterator with input 100...
Benchmarking MapIterator with input 1_000...
Benchmarking MapIterator with input 10_000...
Benchmarking MapIterator with input 1_000_000...
Benchmarking MapKeys with input empty...
Benchmarking MapKeys with input 10...
Benchmarking MapKeys with input 100...
Benchmarking MapKeys with input 1_000...
Benchmarking MapKeys with input 10_000...
Benchmarking MapKeys with input 1_000_000...
Benchmarking MapKeysInverted with input empty...
Benchmarking MapKeysInverted with input 10...
Benchmarking MapKeysInverted with input 100...
Benchmarking MapKeysInverted with input 1_000...
Benchmarking MapKeysInverted with input 10_000...
Benchmarking MapKeysInverted with input 1_000_000...
Benchmarking MapKeysSize with input empty...
Benchmarking MapKeysSize with input 10...
Benchmarking MapKeysSize with input 100...
Benchmarking MapKeysSize with input 1_000...
Benchmarking MapKeysSize with input 10_000...
Benchmarking MapKeysSize with input 1_000_000...
Benchmarking MapKeysSizeInverted with input empty...
Benchmarking MapKeysSizeInverted with input 10...
Benchmarking MapKeysSizeInverted with input 100...
Benchmarking MapKeysSizeInverted with input 1_000...
Benchmarking MapKeysSizeInverted with input 10_000...
Benchmarking MapKeysSizeInverted with input 1_000_000...
Benchmarking MapKeysSizeInverted2 with input empty...
Benchmarking MapKeysSizeInverted2 with input 10...
Benchmarking MapKeysSizeInverted2 with input 100...
Benchmarking MapKeysSizeInverted2 with input 1_000...
Benchmarking MapKeysSizeInverted2 with input 10_000...
Benchmarking MapKeysSizeInverted2 with input 1_000_000...
Benchmarking MapList with input empty...
Benchmarking MapList with input 10...
Benchmarking MapList with input 100...
Benchmarking MapList with input 1_000...
Benchmarking MapList with input 10_000...
Benchmarking MapList with input 1_000_000...

##### With input empty #####
Name                           ips        average  deviation         median         99th %
MapKeysSizeInverted2        3.88 B        0.26 ns ±29446.50%           0 ns           0 ns
MapKeys                     2.42 B        0.41 ns ±15368.46%           0 ns           0 ns
MapKeysSizeInverted         1.03 B        0.97 ns ±19179.40%           0 ns           0 ns
MapKeysInverted             1.03 B        0.97 ns ±19032.95%           0 ns           0 ns
MapKeysSize                 0.81 B        1.24 ns ±16423.31%           0 ns           0 ns
MapIterator               0.0606 B       16.50 ns±176735.88%           0 ns           0 ns
MapList                   0.0595 B       16.79 ns±179400.31%           0 ns           0 ns

Comparison: 
MapKeysSizeInverted2        3.88 B
MapKeys                     2.42 B - 1.60x slower +0.154 ns
MapKeysSizeInverted         1.03 B - 3.75x slower +0.71 ns
MapKeysInverted             1.03 B - 3.77x slower +0.71 ns
MapKeysSize                 0.81 B - 4.81x slower +0.98 ns
MapIterator               0.0606 B - 63.93x slower +16.24 ns
MapList                   0.0595 B - 65.08x slower +16.54 ns

Memory usage statistics:

Name                    Memory usage
MapKeysSizeInverted2             0 B
MapKeys                          0 B - 1.00x memory usage +0 B
MapKeysSizeInverted              0 B - 1.00x memory usage +0 B
MapKeysInverted                  0 B - 1.00x memory usage +0 B
MapKeysSize                      0 B - 1.00x memory usage +0 B
MapIterator                     16 B - ∞ x memory usage +16 B
MapList                          0 B - 1.00x memory usage +0 B

**All measurements for memory usage were the same**

##### With input 10 #####
Name                           ips        average  deviation         median         99th %
MapKeysSizeInverted         8.70 M      114.93 ns ±18028.70%           0 ns           0 ns
MapList                     7.93 M      126.16 ns ±15869.54%           0 ns           0 ns
MapKeysSizeInverted2        7.93 M      126.17 ns ±28655.21%           0 ns           0 ns
MapKeysInverted             7.42 M      134.86 ns ±18452.55%           0 ns           0 ns
MapKeysSize                 7.16 M      139.60 ns ±33923.32%           0 ns           0 ns
MapKeys                     6.26 M      159.69 ns ±33056.23%           0 ns           0 ns
MapIterator                 6.18 M      161.92 ns  ±4808.88%          75 ns         682 ns

Comparison: 
MapKeysSizeInverted         8.70 M
MapList                     7.93 M - 1.10x slower +11.24 ns
MapKeysSizeInverted2        7.93 M - 1.10x slower +11.24 ns
MapKeysInverted             7.42 M - 1.17x slower +19.93 ns
MapKeysSize                 7.16 M - 1.21x slower +24.67 ns
MapKeys                     6.26 M - 1.39x slower +44.76 ns
MapIterator                 6.18 M - 1.41x slower +46.99 ns

Memory usage statistics:

Name                    Memory usage
MapKeysSizeInverted            432 B
MapList                        624 B - 1.44x memory usage +192 B
MapKeysSizeInverted2           432 B - 1.00x memory usage +0 B
MapKeysInverted                432 B - 1.00x memory usage +0 B
MapKeysSize                    432 B - 1.00x memory usage +0 B
MapKeys                        432 B - 1.00x memory usage +0 B
MapIterator                    944 B - 2.19x memory usage +512 B

**All measurements for memory usage were the same**

##### With input 100 #####
Name                           ips        average  deviation         median         99th %
MapKeysSize                 1.77 M      563.49 ns  ±4758.39%         410 ns        1045 ns
MapKeysSizeInverted2        1.77 M      565.48 ns  ±4563.74%         409 ns        1114 ns
MapKeysInverted             1.76 M      568.53 ns  ±4833.96%         406 ns         969 ns
MapKeys                     1.72 M      581.23 ns  ±4522.60%         410 ns        1138 ns
MapKeysSizeInverted         1.70 M      589.11 ns  ±4455.48%         412 ns        1226 ns
MapList                    0.165 M     6075.56 ns  ±1438.19%        5648 ns        7218 ns
MapIterator                0.100 M     9981.93 ns   ±373.97%        9470 ns    15368.26 ns

Comparison: 
MapKeysSize                 1.77 M
MapKeysSizeInverted2        1.77 M - 1.00x slower +1.99 ns
MapKeysInverted             1.76 M - 1.01x slower +5.04 ns
MapKeys                     1.72 M - 1.03x slower +17.74 ns
MapKeysSizeInverted         1.70 M - 1.05x slower +25.62 ns
MapList                    0.165 M - 10.78x slower +5512.08 ns
MapIterator                0.100 M - 17.71x slower +9418.45 ns

Memory usage statistics:

Name                    Memory usage
MapKeysSize                  1.66 KB
MapKeysSizeInverted2         1.66 KB - 1.00x memory usage +0 KB
MapKeysInverted              1.66 KB - 1.00x memory usage +0 KB
MapKeys                      1.66 KB - 1.00x memory usage +0 KB
MapKeysSizeInverted          1.66 KB - 1.00x memory usage +0 KB
MapList                      4.10 KB - 2.48x memory usage +2.45 KB
MapIterator                  7.85 KB - 4.74x memory usage +6.20 KB

**All measurements for memory usage were the same**

##### With input 1_000 #####
Name                           ips        average  deviation         median         99th %
MapKeysSizeInverted        92.57 K       10.80 μs   ±370.75%       10.37 μs       17.51 μs
MapKeysSizeInverted2       92.31 K       10.83 μs   ±383.58%       10.46 μs       15.12 μs
MapKeysInverted            92.25 K       10.84 μs   ±377.81%       10.44 μs       16.05 μs
MapKeysSize                91.93 K       10.88 μs   ±364.95%       10.44 μs       17.31 μs
MapKeys                    91.60 K       10.92 μs   ±443.56%       10.45 μs       16.22 μs
MapList                    13.15 K       76.03 μs   ±113.66%       73.94 μs      113.63 μs
MapIterator                 8.53 K      117.18 μs   ±100.61%      114.48 μs      187.49 μs

Comparison: 
MapKeysSizeInverted        92.57 K
MapKeysSizeInverted2       92.31 K - 1.00x slower +0.0308 μs
MapKeysInverted            92.25 K - 1.00x slower +0.0378 μs
MapKeysSize                91.93 K - 1.01x slower +0.0750 μs
MapKeys                    91.60 K - 1.01x slower +0.115 μs
MapList                    13.15 K - 7.04x slower +65.22 μs
MapIterator                 8.53 K - 10.85x slower +106.38 μs

Memory usage statistics:

Name                    Memory usage
MapKeysSizeInverted            376 B
MapKeysSizeInverted2           376 B - 1.00x memory usage +0 B
MapKeysInverted                376 B - 1.00x memory usage +0 B
MapKeysSize                    376 B - 1.00x memory usage +0 B
MapKeys                        376 B - 1.00x memory usage +0 B
MapList                      31072 B - 82.64x memory usage +30696 B
MapIterator                  59032 B - 157.00x memory usage +58656 B

**All measurements for memory usage were the same**

##### With input 10_000 #####
Name                           ips        average  deviation         median         99th %
MapKeysInverted             7.32 K      136.66 μs    ±83.55%      133.51 μs      192.85 μs
MapKeys                     7.30 K      137.08 μs   ±140.44%      133.47 μs      192.50 μs
MapKeysSizeInverted         7.29 K      137.21 μs    ±84.16%      133.58 μs      192.44 μs
MapKeysSizeInverted2        7.28 K      137.35 μs   ±141.76%      133.47 μs      193.81 μs
MapKeysSize                 7.26 K      137.66 μs   ±135.18%      133.56 μs      196.65 μs
MapList                     0.94 K     1060.35 μs    ±51.35%     1023.87 μs     1281.27 μs
MapIterator                 0.65 K     1528.56 μs    ±26.34%     1487.01 μs     1792.09 μs

Comparison: 
MapKeysInverted             7.32 K
MapKeys                     7.30 K - 1.00x slower +0.42 μs
MapKeysSizeInverted         7.29 K - 1.00x slower +0.56 μs
MapKeysSizeInverted2        7.28 K - 1.01x slower +0.70 μs
MapKeysSize                 7.26 K - 1.01x slower +1.00 μs
MapList                     0.94 K - 7.76x slower +923.69 μs
MapIterator                 0.65 K - 11.19x slower +1391.91 μs

Memory usage statistics:

Name                    Memory usage
MapKeysInverted                512 B
MapKeys                        512 B - 1.00x memory usage +0 B
MapKeysSizeInverted            512 B - 1.00x memory usage +0 B
MapKeysSizeInverted2           512 B - 1.00x memory usage +0 B
MapKeysSize                    512 B - 1.00x memory usage +0 B
MapList                     601280 B - 1174.38x memory usage +600768 B
MapIterator                 802936 B - 1568.23x memory usage +802424 B

**All measurements for memory usage were the same**

##### With input 1_000_000 #####
Name                           ips        average  deviation         median         99th %
MapKeysSize                  73.69       13.57 ms    ±16.50%       13.37 ms       14.74 ms
MapKeysSizeInverted          73.68       13.57 ms    ±17.54%       13.35 ms       14.58 ms
MapKeys                      73.18       13.67 ms    ±16.88%       13.42 ms       16.79 ms
MapKeysSizeInverted2         72.98       13.70 ms    ±18.87%       13.36 ms       16.05 ms
MapKeysInverted              72.90       13.72 ms    ±16.35%       13.51 ms       14.78 ms
MapList                       5.56      179.88 ms    ±10.68%      177.22 ms      224.71 ms
MapIterator                   3.85      259.86 ms     ±4.91%      256.98 ms      290.22 ms

Comparison: 
MapKeysSize                  73.69
MapKeysSizeInverted          73.68 - 1.00x slower +0.00290 ms
MapKeys                      73.18 - 1.01x slower +0.0952 ms
MapKeysSizeInverted2         72.98 - 1.01x slower +0.132 ms
MapKeysInverted              72.90 - 1.01x slower +0.147 ms
MapList                       5.56 - 13.26x slower +166.31 ms
MapIterator                   3.85 - 19.15x slower +246.29 ms

Memory usage statistics:

Name                    Memory usage
MapKeysSize                    712 B
MapKeysSizeInverted            712 B - 1.00x memory usage +0 B
MapKeys                        712 B - 1.00x memory usage +0 B
MapKeysSizeInverted2           712 B - 1.00x memory usage +0 B
MapKeysInverted                712 B - 1.00x memory usage +0 B
MapList                   40397984 B - 56738.74x memory usage +40397272 B
MapIterator               73403144 B - 103094.30x memory usage +73402432 B
```

You can see the implementation here.

What I think is that optimizing for the fastest of all operations, which is an empty map (3.8 billion operations per second) is detrimental for the other operations, i.e. the non-empty maps.

I think `MapKeysSizeInverted` is the best of them all.

**Comment by eksperimental** [comment]
Once we agree on which one should we choose, I can go ahead an update the other PR.

**Comment by Qqwy** [comment]
> I think MapKeysSizeInverted is the best of them all.

Probably. Could you share the implementation of that one? What exactly is inverted?

**Comment by eksperimental** [comment]
Sorry, the link didn't get pasted
https://github.com/eksperimental/elixir-extractable/blob/faster_map_extract/benchmarks/map_extract.exs

**Comment by Qqwy** [comment]
The results of your benchmark are quite interesting. 

For the smaller inputs, the standard deviation is ridiculously large, so we probably end up measuring GC time or other non-deterministic things that might happen in the background and overshadow the implementation itself.

I actually expect that the resulting BEAM bytecode between  `MapKeysSize`, `MapKeysSizeInverted` and `MapKeysSizeInverted2` would be the same.
(_I'll check this_).

**Comment by Qqwy** [comment]
Turns out they are _not_ the same. Essentially the differences introduced in the code by ourselves are still there:

- `MapKeysSize` vs`MapKeysSizeInverted` has the tests in the opposite orders.
- `MapKeysSizeInverted2` has the extra `map_size`-check in there (raising when a non-map is entered), whereas the others just always return `{:error, empty}`.

It actually is not strange that the compiler does _not_ optimize here because thinking more about it, it would alter the semantics of the code.

In this particular case, we (humans) know that this particular `extract` will only ever be called with a map because it is in a protocol, but the BEAM compiler doesn't know this, so it has to keep the order of the clauses and the extra checks intact.

This explains why `MapKeysSizeInverted` beats the others for small maps.

**Comment by eksperimental** [comment]
I guess this one can be closed

**Pull request closed without merging**
